wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    - 1: loss_epoch
      5: 1
      6:
      - 1
    - 1: val_acc_step
      5: 1
      6:
      - 1
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: val_acc_epoch
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: active_val_acc
      5: 1
      6:
      - 1
    - 1: examples
      5: 1
      6:
      - 1
    - 1: active_val_acc_epoch
      5: 1
      6:
      - 1
    - 1: active_val_loss
      5: 1
      6:
      - 1
    - 1: active_val_loss_epoch
      5: 1
      6:
      - 1
    - 1: test_acc_step
      5: 1
      6:
      - 1
    - 1: test_loss_step
      5: 1
      6:
      - 1
    - 1: test_acc_epoch
      5: 1
      6:
      - 1
    - 1: test_loss_epoch
      5: 1
      6:
      - 1
    python_version: 3.9.7
    start_time: 1640166049
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      2:
      - 1
      - 5
      - 9
      - 11
      3:
      - 7
      4: 3.9.7
      5: 0.12.7
      6: 4.12.5
      8:
      - 5
