wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.1
    start_time: 1639484047
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      4: 3.9.1
      5: 0.12.7
      6: 4.12.5
      8:
      - 5
