#!/bin/bash

#SBATCH --partition=gpu_short
#SBATCH --gres=gpu:1
#SBATCH --job-name=test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:03:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/active_learning

# copy all data from home folder to SCRATCH
cp -r $HOME/active_learning/resources/. "$TMPDIR"

# create folder on scratch disk to store output
mkdir "$TMPDIR"/ard_output_dir

# Your job starts in the directory where you call sbatch
cd $HOME/active_learning
# Activate your environment
source activate active

# Run your code
srun python main.py --input_dir "$TMPDIR/ard_data" --output_dir "$TMPDIR/ard_output_dir" --downsample_rate=0.01 --acquisition_fn=least-confidence

cp -r "$TMPDIR"/ard_output_dir $HOME/active_learning/results