#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:3
#SBATCH --job-name=multi_gpu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:30:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/active_learning

# copy all data from home folder to SCRATCH
cp -r $HOME/active_learning/resources/. "$TMPDIR"

# create folder on scratch disk to store output
mkdir "$TMPDIR"/ard_output_dir

# Your job starts in the directory where you call sbatch
cd $HOME/active_learning
# Activate your environment
source activate active

# Run your code
srun python main.py \
            --input_dir "$TMPDIR/ard_data" \
            --output_dir "$TMPDIR/ard_output_dir" \
            --model_id="bert-base-uncased" \
            --batch_size=16 \
            --acquisition_fn="max-entropy" \
            --labelling_batch_size=0.02 \
            --seed_size=0.02 \
            --downsample_rate=0.05 \
            --log_every=2 \
            --refresh_rate=25 \
            --debug=True \
            --seed=43 \
            --iterations=10 \
            --num_workers=3 \
            --uid="gather" \

cp -r "$TMPDIR"/ard_output_dir $HOME/active_learning/results