wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.8
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1641999063
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      4: 3.9.7
      5: 0.12.8
      6: 4.12.5
      8:
      - 5
