#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=test_run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/active_learning

# copy all data from home folder to SCRATCH
cp -r $HOME/active_learning/resources/. "$TMPDIR"

# create folder on scratch disk to store output
mkdir "$TMPDIR"/ard_output_dir_checkpoints
mkdir "$TMPDIR"/ard_output_dir_results

# Your job starts in the directory where you call sbatch
cd $HOME/active_learning
# Activate your environment
source activate active

# Run your code
srun python main.py \
            --input_dir "$TMPDIR/ard_data" \
            --output_dir "$TMPDIR/ard_output_dir_results" \
            --checkpoint_dir "$TMPDIR/ard_output_dir_checkpoints" \
            --project_dir="test" \
            --array_uid="repeated model failure reproduction test oom failure normal precision" \
            --model_id="roberta-large" \
            --train_sets="SNLI_1.0" \
            --dev_sets="SNLI" \
            --test_sets="SNLI" \
            --seed_size=1.0 \
            --downsample_rate=0.05\
            --labelling_batch_size=0 \
            --al_iterations=0 \
            --dropout=0.3 \
            --mc_iterations=4 \
            --lr=5e-6 \
            --batch_size=8 \
            --accumulate_grad_batches=4 \
            --max_epochs=10 \
            --min_epochs=10 \
            --patience=20 \
            --monitor="val_acc" \
            --progress_bar \
            --num_workers=0 \
            --precision=16 \
            --log_every=1 \
            --refresh_rate=25 \
            --acquisition_fn="random" \
            --seed=42 \

cp -r "$TMPDIR"/ard_output_dir_results $HOME/active_learning/results