#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=array_run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=4:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/output_%A_%a.out
#SBATCH --array=1-5%5

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/active_learning

# copy all data from home folder to SCRATCH
cp -r $HOME/active_learning/resources/. "$TMPDIR"

# create folder on scratch disk to store output
mkdir "$TMPDIR"/ard_output_dir_checkpoints
mkdir "$TMPDIR"/ard_output_dir_results

# Your job starts in the directory where you call sbatch
cd $HOME/active_learning
# Activate your environment
source activate active

HPARAMS_FILE=$HOME/active_learning/new_jobs/hparams/array_job_hyperparameters_random.txt

# Run your code
srun python main.py \
            --input_dir "$TMPDIR/ard_data" \
            --output_dir "$TMPDIR/ard_output_dir_results" \
            --checkpoint_dir "$TMPDIR/ard_output_dir_checkpoints" \
            --project_dir="test" \
            --array_uid="OOD MNLI active learning test elke 25 steps check testje 5" \
            --model_id="roberta-large" \
            --train_sets="SNLI_1.0,ANLI_1.0,WANLI_1.0" \
            --dev_sets="SNLI,ANLI,WANLI" \
            --ood_sets="MNLI" \
            --test_sets="SNLI,ANLI,WANLI,MNLI" \
            --max_dev_size=2200\
            --seed_size=500 \
            --downsample_rate=0.05\
            --labelling_batch_size=250 \
            --al_iterations=14 \
            --dropout=0.3 \
            --mc_iterations=4 \
            --lr=5e-6 \
            --batch_size=8 \
            --accumulate_grad_batches=4 \
            --patience=10 \
            --val_check_interval=50 \
            --monitor="val_acc" \
            --progress_bar \
            --num_workers=0 \
            --precision=16 \
            --log_every=1 \
            --refresh_rate=25 \
            $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)

cp -r "$TMPDIR"/ard_output_dir_results $HOME/active_learning/results