#!/bin/bash

#SBATCH --partition=gpu_titanrtx_short
#SBATCH --gres=gpu:1
#SBATCH --job-name=test_run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:10:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/active_learning

# copy all data from home folder to SCRATCH
cp -r $HOME/active_learning/resources/. "$TMPDIR"

# create folder on scratch disk to store output
mkdir "$TMPDIR"/ard_output_dir_checkpoints
mkdir "$TMPDIR"/ard_output_dir_results

# Your job starts in the directory where you call sbatch
cd $HOME/active_learning
# Activate your environment
source activate active

# Run your code
srun python main.py \
            --input_dir "$TMPDIR/ard_data" \
            --output_dir "$TMPDIR/ard_output_dir_results" \
            --checkpoint_dir "$TMPDIR/ard_output_dir_checkpoints" \
            --project_dir="test" \
            --array_uid="sub-epoch-eval test" \
            --model_id="bert-base-uncased" \
            --datasets="MNLI" \
            --checkpoint_datasets="MNLI" \
            --downsample_rate=1.0 \
            --seed_size=0.02 \
            --labelling_batch_size=0.02 \
            --al_iterations=24 \
            --acquisition_fn="random" \
            --dropout=0.3 \
            --lr=2e-5 \
            --batch_size=32 \
            --max_epochs=4 \
            --patience=3 \
            --monitor="val_loss" \
            --num_workers=3 \
            --precision=16 \
            --log_every=2 \
            --progress_bar \
            --refresh_rate=25 \
            --seed=41 \

cp -r "$TMPDIR"/ard_output_dir_results $HOME/active_learning/results