#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:1
#SBATCH --job-name=AL_generic
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:25:00
#SBATCH --mem=32000M
#SBATCH --output=slurm/AL_test_jobs/output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/active_learning

# copy all data from home folder to SCRATCH
cp -r $HOME/active_learning/resources/. "$TMPDIR"

# create folder on scratch disk to store output
mkdir "$TMPDIR"/ard_output_dir_checkpoints
mkdir "$TMPDIR"/ard_output_dir_results

# Your job starts in the directory where you call sbatch
cd $HOME/active_learning
# Activate your environment
source activate active

# Run your code
srun python main.py \
            --input_dir "$TMPDIR/ard_data" \
            --output_dir "$TMPDIR/ard_output_dir_results" \
            --checkpoint_dir "$TMPDIR/ard_output_dir_checkpoints" \
            --model_id="bert-base-uncased" \
            --batch_size=32 \
            --acquisition_fn="bald" \
            --labelling_batch_size=0.02 \
            --seed_size=0.02 \
            --downsample_rate=0.01 \
            --log_every=2 \
            --refresh_rate=25 \
            --seed=42 \
            --al_iterations=10 \
            --num_workers=8 \
            --precision=16 \
            --dropout=0.3 \
            --lr=2e-5 \
            --max_epochs=1 \
            --monitor="val_loss" \
            --uid="generic_tests" \


cp -r "$TMPDIR"/ard_output_dir_results $HOME/active_learning/results